version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: family_app
    ports:
      - "5432:5432"
    volumes:
      - family_app_pg_data:/var/lib/postgresql/data

volumes:
  family_app_pg_data:
